# See https://github.com/docker-library/php/blob/4677ca134fe48d20c820a19becb99198824d78e3/7.0/fpm/Dockerfile
FROM php:7.1-fpm

MAINTAINER Sebastian Thadewald <sebastian@wondrous.ch>

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    mysql-client \
    libxml2-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libmcrypt-dev \
    libpng12-dev

RUN apt install wget -y

RUN docker-php-ext-install mysqli
RUN docker-php-ext-install soap
RUN docker-php-ext-install zip
RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
RUN docker-php-ext-install gd
RUN docker-php-ext-install mcrypt

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer --version

# Set timezone
RUN rm /etc/localtime
RUN ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime
RUN "date"

RUN wget http://ftp.hosteurope.de/mirror/packages.dotdeb.org/pool/all/p/pcre3/libpcre3_8.39-1~dotdeb%2b8.1_amd64.deb
RUN dpkg -i libpcre3_8.39-1~dotdeb+8.1_amd64.deb

# Type docker-php-ext-install to see available extensions
RUN docker-php-ext-install pdo pdo_mysql

ADD www.conf /usr/local/etc/php-fpm.d/
ADD php.ini /usr/local/etc/php/


WORKDIR /var/www/web

CMD ["php-fpm"]
